DROP TABLE IF EXISTS grojjitems;

BEGIN;

CREATE TABLE grojjitems(
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  price VARCHAR NOT NULL,
  condition VARCHAR NOT NULL,
  likes INT NOT NULL DEFAULT 0,
  url TEXT,
  sellerid TEXT NOT NULL
);

COMMIT;
